version: '3.8'

services:
  PostgreSQL:
    image: postgres:14.3
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books-db
    ports:
      - "5433:5432"
    restart: always


